travis:
  secure:
    BINSTAR_TOKEN: eeIzP4pTXA+VYkWsIssgy5x8QZPc1oRAWQHiWTzErQAVfn+c3Q72Dl4DmJ7RRsogplspmuQM35DwF/tCDxO3ICUVJhOODbxp0ylMg1XigIN3GhLgACl6j2mASot5RKmKhfLSQYmXdna3krV1+f5DILo9kDus0RTMR6zyz5SeDVRyzqYHVktTupyfOpA1QGJM9XepmdZCozT5UmfJgPBYsSYiNxhM/J5kmyuCuwUSfWLlfBGrX3gfZRCXkTkX/9lyYdQL1UOw25OlY+uVfPXmIdVZndPtZ2KhJXiyyKpChOcS3vG4ZIsZIXqYzrXSSGofv2sACNDAiYGPHemr1ejtmqixbRiybODsCPNR0VzXaz9F6+7w2t/AUGdYDT4sxFPE5qy02Sj5owHhi4n8yPFPXrZUFKf5am4clT84C/sbycNJFu2A/9Ox3YW3boS559OLooqCbT1IX7Xr11mOblGRBkpskCIdEVIoydchwflPvYE8Oi4xrlgS61hVIdJFIfWKDSM2ylls1T+lQSqeEKJDdS1PUlDe6rfSzYq1Qh1V654ElxfMo97FpmqLt6lAbu6wGf1cWLH3cVur/PPiLRrGeaLx8ZwaplaQfeNHHdlLQLLwrw43fzXM1GOlj0B1SJtgAxDG86dELoB+iRpAW9IMdMJTu81jV3oyny8TjbMwCm0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
